---
title: "Calculating and Comparing Bicycle Gears"
output: github_document
always_allow_html: true
---

**Credit:** the code in bicycle_gears.R was written by David Roberts and described in his April 6 2016 blog post from [Cycling gear ratio calculator for R (or why you should just go buy a SRAM Eagle 1×12 group right now)](https://davidrroberts.wordpress.com/2016/04/06/cycling-gear-ratio-calculator-for-r-or-why-you-should-just-go-buy-a-sram-eagle-1x12-group-right-now/). 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```


* Functions are in `R/bicycle_gears.R`.
* Data is in `data/cassette_key.csv`.

## Read in data and functions


```{r}
library(dplyr)
cassette_key <- readr::read_csv('data/cassette_key.csv')

cassette_key ## todo make interactive table
```

```{r two-plus-two, exercise=TRUE}
source('R/bicycle_gears.R')
```


## Make a plot comparing 1x and 2x options

```{r}
twoby_rings <- c(39, 53)
# 11-speed 12-28 on the rear
oneby_rings <- 44
twoby_cogs <- getCogs("Road","Shimano", speeds = 11, small = 12, large = 28)

oneby_cogs <- getCogs("Mountain", "Sram", speeds = 12, small = 10, large = 50)
# Running 700x23c
myWheel <- wheelSize(622, 23, "mm")

two <- cbind(type = '2x', bind_rows(getGears(twoby_rings, twoby_cogs, myWheel)))
one <- cbind(type = '1x', bind_rows(getGears(oneby_rings, oneby_cogs, myWheel)))
all <- rbind(one, two) %>% mutate(rings = as.factor(chainring), offset = ifelse(chainring == 53, 1, 0))


library(ggplot2)
# ggplot(data = all, aes(cog, gearInches, color = type, shape = rings)) + 
#   geom_point() +
#   geom_line()

ggplot(data = all, aes(type, gearInches, color = rings)) + 
  geom_point(aes(size = cog),alpha=0.5) +
  geom_line() +
  scale_color_grey() +
  geom_label(aes(label = cog), nudge_x = 0.1, size = 3, label.size= 0,alpha=0) +
  #scale_size_binned_area() +
  theme_bw() +
  coord_flip()

## todo: nudge 2x rings apart
## clean up fig
## make a shiny app
## make an R package
```

